import { MigrationInterface, QueryRunner } from "typeorm";

export class FakePosts1678594062135 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(
      `
        insert into catch_entity (note, "imageUri", "predictionId") values ('Integer non velit.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 1);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Mauris sit amet eros.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 2);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Cras in purus eu magna vulputate luctus.', 'http://dummyimage.com/256x256.png/dddddd/000000', 3);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Integer tincidunt ante vel ipsum.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 4);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 5);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Vestibulum ac est lacinia nisi venenatis tristique.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 6);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Proin risus.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 7);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 8);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Donec dapibus.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 9);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 10);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Quisque porta volutpat erat.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 11);
        insert into catch_entity (note, "imageUri", "predictionId") values ('In blandit ultrices enim.', 'http://dummyimage.com/256x256.png/dddddd/000000', 12);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Mauris lacinia sapien quis libero.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 13);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Nulla mollis molestie lorem.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 14);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Cras pellentesque volutpat dui.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 15);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Maecenas pulvinar lobortis est.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 16);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Nulla nisl.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 17);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/ff4444/ffffff', 18);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Aliquam quis turpis eget elit sodales scelerisque.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 19);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/cc0000/ffffff', 20);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Etiam justo.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 21);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/cc0000/ffffff', 22);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/ff4444/ffffff', 23);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Proin interdum mauris non ligula pellentesque ultrices.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 24);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'http://dummyimage.com/256x256.png/dddddd/000000', 25);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/dddddd/000000', 26);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Donec vitae nisi.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 27);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Phasellus sit amet erat.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 28);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/cc0000/ffffff', 29);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'http://dummyimage.com/256x256.png/dddddd/000000', 30);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Maecenas tincidunt lacus at velit.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 31);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Ut at dolor quis odio consequat varius.', 'http://dummyimage.com/256x256.png/dddddd/000000', 32);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Morbi quis tortor id nulla ultrices aliquet.', 'http://dummyimage.com/256x256.png/dddddd/000000', 33);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/dddddd/000000', 34);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Nulla nisl.', 'http://dummyimage.com/256x256.png/dddddd/000000', 35);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Donec ut dolor.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 36);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Aenean auctor gravida sem.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 37);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 38);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 39);
        insert into catch_entity (note, "imageUri", "predictionId") values ('In hac habitasse platea dictumst.', 'http://dummyimage.com/256x256.png/dddddd/000000', 40);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Aenean lectus.', 'http://dummyimage.com/256x256.png/dddddd/000000', 41);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Phasellus id sapien in sapien iaculis congue.', 'http://dummyimage.com/256x256.png/dddddd/000000', 42);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Morbi porttitor lorem id ligula.', 'http://dummyimage.com/256x256.png/dddddd/000000', 43);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Donec dapibus.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 44);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 45);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Fusce consequat.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 46);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 47);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 48);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 49);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Curabitur in libero ut massa volutpat convallis.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 50);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Pellentesque eget nunc.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 51);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Ut tellus.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 52);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Sed ante.', 'http://dummyimage.com/256x256.png/dddddd/000000', 53);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Nulla tellus.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 54);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Pellentesque ultrices mattis odio.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 55);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Phasellus id sapien in sapien iaculis congue.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 56);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Morbi ut odio.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 57);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Integer tincidunt ante vel ipsum.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 58);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Duis consequat dui nec nisi volutpat eleifend.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 59);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 60);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 61);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/cc0000/ffffff', 62);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 63);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'http://dummyimage.com/256x256.png/dddddd/000000', 64);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/cc0000/ffffff', 65);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Aenean fermentum.', 'http://dummyimage.com/256x256.png/dddddd/000000', 66);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Praesent blandit.', 'http://dummyimage.com/256x256.png/dddddd/000000', 67);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 68);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/cc0000/ffffff', 69);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Suspendisse potenti.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 70);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Duis aliquam convallis nunc.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 71);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 72);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/dddddd/000000', 73);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Vivamus tortor.', 'http://dummyimage.com/256x256.png/dddddd/000000', 74);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Aliquam sit amet diam in magna bibendum imperdiet.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 75);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/ff4444/ffffff', 76);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/cc0000/ffffff', 77);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Maecenas pulvinar lobortis est.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 78);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Maecenas rhoncus aliquam lacus.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 79);
        insert into catch_entity (note, "imageUri", "predictionId") values ('In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 80);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/ff4444/ffffff', 81);
        insert into catch_entity (note, "imageUri", "predictionId") values ('In congue.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 82);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Curabitur in libero ut massa volutpat convallis.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 83);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Integer non velit.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 84);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Phasellus in felis.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 85);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Aenean sit amet justo.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 86);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Proin interdum mauris non ligula pellentesque ultrices.', 'http://dummyimage.com/256x256.png/cc0000/ffffff', 87);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Vivamus vestibulum sagittis sapien.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 88);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 89);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Duis bibendum.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 90);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Duis aliquam convallis nunc.', 'http://dummyimage.com/256x256.png/dddddd/000000', 91);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Aenean sit amet justo.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 92);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 93);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'http://dummyimage.com/256x256.png/dddddd/000000', 94);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Mauris lacinia sapien quis libero.', 'http://dummyimage.com/256x256.png/ff4444/ffffff', 95);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/dddddd/000000', 96);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Quisque ut erat.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 97);
        insert into catch_entity (note, "imageUri", "predictionId") values ('In congue.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 98);
        insert into catch_entity (note, "imageUri", "predictionId") values (null, 'http://dummyimage.com/256x256.png/dddddd/000000', 99);
        insert into catch_entity (note, "imageUri", "predictionId") values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'http://dummyimage.com/256x256.png/5fa2dd/ffffff', 100);

        insert into post_entity ("creatorId", text, "catchId") values (3, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1);
        insert into post_entity ("creatorId", text, "catchId") values (9, 'Suspendisse potenti. In eleifend quam a odio.', 2);
        insert into post_entity ("creatorId", text, "catchId") values (19, 'Nam tristique tortor eu pede.', 3);
        insert into post_entity ("creatorId", text, "catchId") values (7, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 4);
        insert into post_entity ("creatorId", text, "catchId") values (12, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 5);
        insert into post_entity ("creatorId", text, "catchId") values (19, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 6);
        insert into post_entity ("creatorId", text, "catchId") values (9, 'Nam tristique tortor eu pede.', 7);
        insert into post_entity ("creatorId", text, "catchId") values (24, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 8);
        insert into post_entity ("creatorId", text, "catchId") values (1, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 9);
        insert into post_entity ("creatorId", text, "catchId") values (2, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 10);
        insert into post_entity ("creatorId", text, "catchId") values (3, 'In eleifend quam a odio. In hac habitasse platea dictumst.', 11);
        insert into post_entity ("creatorId", text, "catchId") values (9, 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 12);
        insert into post_entity ("creatorId", text, "catchId") values (15, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 13);
        insert into post_entity ("creatorId", text, "catchId") values (23, 'Morbi quis tortor id nulla ultrices aliquet.', 14);
        insert into post_entity ("creatorId", text, "catchId") values (14, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 15);
        insert into post_entity ("creatorId", text, "catchId") values (23, 'In quis justo. Maecenas rhoncus aliquam lacus.', 16);
        insert into post_entity ("creatorId", text, "catchId") values (17, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 17);
        insert into post_entity ("creatorId", text, "catchId") values (4, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', 18);
        insert into post_entity ("creatorId", text, "catchId") values (12, 'Vivamus vestibulum sagittis sapien.', 19);
        insert into post_entity ("creatorId", text, "catchId") values (18, 'Fusce posuere felis sed lacus.', 20);
        insert into post_entity ("creatorId", text, "catchId") values (20, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 21);
        insert into post_entity ("creatorId", text, "catchId") values (21, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 22);
        insert into post_entity ("creatorId", text, "catchId") values (5, 'Donec posuere metus vitae ipsum.', 23);
        insert into post_entity ("creatorId", text, "catchId") values (17, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 24);
        insert into post_entity ("creatorId", text, "catchId") values (20, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 25);
        insert into post_entity ("creatorId", text, "catchId") values (17, 'Pellentesque ultrices mattis odio. Donec vitae nisi.', 26);
        insert into post_entity ("creatorId", text, "catchId") values (12, 'Nulla tellus. In sagittis dui vel nisl.', 27);
        insert into post_entity ("creatorId", text, "catchId") values (20, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 28);
        insert into post_entity ("creatorId", text, "catchId") values (18, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 29);
        insert into post_entity ("creatorId", text, "catchId") values (17, 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 30);
        insert into post_entity ("creatorId", text, "catchId") values (16, 'Vivamus in felis eu sapien cursus vestibulum.', 31);
        insert into post_entity ("creatorId", text, "catchId") values (8, 'Nam tristique tortor eu pede.', 32);
        insert into post_entity ("creatorId", text, "catchId") values (21, 'Integer tincidunt ante vel ipsum.', 33);
        insert into post_entity ("creatorId", text, "catchId") values (4, 'Donec posuere metus vitae ipsum.', 34);
        insert into post_entity ("creatorId", text, "catchId") values (6, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 35);
        insert into post_entity ("creatorId", text, "catchId") values (8, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 36);
        insert into post_entity ("creatorId", text, "catchId") values (19, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 37);
        insert into post_entity ("creatorId", text, "catchId") values (17, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 38);
        insert into post_entity ("creatorId", text, "catchId") values (17, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 39);
        insert into post_entity ("creatorId", text, "catchId") values (10, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 40);
        insert into post_entity ("creatorId", text, "catchId") values (1, 'Morbi porttitor lorem id ligula.', 41);
        insert into post_entity ("creatorId", text, "catchId") values (3, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 42);
        insert into post_entity ("creatorId", text, "catchId") values (10, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 43);
        insert into post_entity ("creatorId", text, "catchId") values (16, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 44);
        insert into post_entity ("creatorId", text, "catchId") values (20, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 45);
        insert into post_entity ("creatorId", text, "catchId") values (4, 'Curabitur at ipsum ac tellus semper interdum.', 46);
        insert into post_entity ("creatorId", text, "catchId") values (22, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 47);
        insert into post_entity ("creatorId", text, "catchId") values (21, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 48);
        insert into post_entity ("creatorId", text, "catchId") values (2, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 49);
        insert into post_entity ("creatorId", text, "catchId") values (7, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 50);
        insert into post_entity ("creatorId", text, "catchId") values (21, 'Ut tellus.', 51);
        insert into post_entity ("creatorId", text, "catchId") values (11, 'Donec dapibus. Duis at velit eu est congue elementum.', 52);
        insert into post_entity ("creatorId", text, "catchId") values (13, 'Proin at turpis a pede posuere nonummy. Integer non velit.', 53);
        insert into post_entity ("creatorId", text, "catchId") values (20, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 54);
        insert into post_entity ("creatorId", text, "catchId") values (17, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 55);
        insert into post_entity ("creatorId", text, "catchId") values (3, 'In congue. Etiam justo.', 56);
        insert into post_entity ("creatorId", text, "catchId") values (1, 'Suspendisse potenti.', 57);
        insert into post_entity ("creatorId", text, "catchId") values (18, 'Quisque id justo sit amet sapien dignissim vestibulum.', 58);
        insert into post_entity ("creatorId", text, "catchId") values (16, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 59);
        insert into post_entity ("creatorId", text, "catchId") values (10, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 60);
        insert into post_entity ("creatorId", text, "catchId") values (17, 'Quisque ut erat. Curabitur gravida nisi at nibh.', 61);
        insert into post_entity ("creatorId", text, "catchId") values (13, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 62);
        insert into post_entity ("creatorId", text, "catchId") values (21, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 63);
        insert into post_entity ("creatorId", text, "catchId") values (1, 'Nulla ut erat id mauris vulputate elementum.', 64);
        insert into post_entity ("creatorId", text, "catchId") values (10, 'Morbi porttitor lorem id ligula.', 65);
        insert into post_entity ("creatorId", text, "catchId") values (6, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 66);
        insert into post_entity ("creatorId", text, "catchId") values (10, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 67);
        insert into post_entity ("creatorId", text, "catchId") values (12, 'Integer a nibh.', 68);
        insert into post_entity ("creatorId", text, "catchId") values (24, 'In hac habitasse platea dictumst.', 69);
        insert into post_entity ("creatorId", text, "catchId") values (3, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 70);
        insert into post_entity ("creatorId", text, "catchId") values (17, 'Integer tincidunt ante vel ipsum.', 71);
        insert into post_entity ("creatorId", text, "catchId") values (10, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 72);
        insert into post_entity ("creatorId", text, "catchId") values (21, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 73);
        insert into post_entity ("creatorId", text, "catchId") values (9, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 74);
        insert into post_entity ("creatorId", text, "catchId") values (24, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 75);
        insert into post_entity ("creatorId", text, "catchId") values (19, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 76);
        insert into post_entity ("creatorId", text, "catchId") values (5, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 77);
        insert into post_entity ("creatorId", text, "catchId") values (4, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 78);
        insert into post_entity ("creatorId", text, "catchId") values (20, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 79);
        insert into post_entity ("creatorId", text, "catchId") values (19, 'Etiam justo.', 80);
        insert into post_entity ("creatorId", text, "catchId") values (1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 81);
        insert into post_entity ("creatorId", text, "catchId") values (4, 'Cras in purus eu magna vulputate luctus.', 82);
        insert into post_entity ("creatorId", text, "catchId") values (14, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 83);
        insert into post_entity ("creatorId", text, "catchId") values (14, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 84);
        insert into post_entity ("creatorId", text, "catchId") values (8, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 85);
        insert into post_entity ("creatorId", text, "catchId") values (9, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 86);
        insert into post_entity ("creatorId", text, "catchId") values (24, 'Pellentesque ultrices mattis odio.', 87);
        insert into post_entity ("creatorId", text, "catchId") values (16, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 88);
        insert into post_entity ("creatorId", text, "catchId") values (22, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 89);
        insert into post_entity ("creatorId", text, "catchId") values (22, 'Fusce consequat. Nulla nisl.', 90);
        insert into post_entity ("creatorId", text, "catchId") values (10, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 91);
        insert into post_entity ("creatorId", text, "catchId") values (3, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 92);
        insert into post_entity ("creatorId", text, "catchId") values (5, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 93);
        insert into post_entity ("creatorId", text, "catchId") values (8, 'Phasellus in felis. Donec semper sapien a libero.', 94);
        insert into post_entity ("creatorId", text, "catchId") values (11, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 95);
        insert into post_entity ("creatorId", text, "catchId") values (19, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', 96);
        insert into post_entity ("creatorId", text, "catchId") values (18, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 97);
        insert into post_entity ("creatorId", text, "catchId") values (13, 'Praesent blandit lacinia erat.', 98);
        insert into post_entity ("creatorId", text, "catchId") values (9, 'Curabitur in libero ut massa volutpat convallis.', 99);
        insert into post_entity ("creatorId", text, "catchId") values (19, 'Aliquam sit amet diam in magna bibendum imperdiet.', 100);
        `
    );
  }

  public async down(_: QueryRunner): Promise<void> {}
}
