import { MigrationInterface, QueryRunner } from "typeorm";

export class FakeUsers1678592553127 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(
      `
      insert into user_entity (username, email, password, "profilePicUrl") values ('gong0', 'dkillock0@illinois.edu', 'hLgNonfQb8', 'http://dummyimage.com/199x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('oronayne1', 'okeatch1@virginia.edu', 'oPAPzGBvwaO', 'http://dummyimage.com/204x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('cvasyutichev2', 'aoldman2@vinaora.com', 'JKPR1xX6Fa9', 'http://dummyimage.com/230x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('jpoolton3', 'pkneeshaw3@pcworld.com', 'TBGfEo1', 'http://dummyimage.com/178x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('imatterface4', 'gbinion4@blog.com', '4lSU2qWz', 'http://dummyimage.com/142x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('pdytham5', 'cpimerick5@blog.com', 'dw58JvsZht', 'http://dummyimage.com/117x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('rgiorgetti6', 'fdeares6@newsvine.com', 'yA77Ttd0QY4', 'http://dummyimage.com/238x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('bsims7', 'tcabedo7@purevolume.com', 'Xm7z32ORH', 'http://dummyimage.com/132x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('lcannavan8', 'fbriiginshaw8@bloglovin.com', 'GWMI3DLG', 'http://dummyimage.com/167x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('adodle9', 'ecrasford9@google.cn', 'EP2bPAdnAn', 'http://dummyimage.com/131x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('emowbraya', 'gfisbya@de.vu', '9caurtuHIHOq', 'http://dummyimage.com/161x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('mebbottsb', 'tdelieub@google.com.br', 'cwdNLJFfh', 'http://dummyimage.com/163x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('tlightowlersc', 'mfollettc@sohu.com', 'duvp6m', 'http://dummyimage.com/195x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('kjaquestd', 'dkitchasided@tmall.com', 'zvOqsKpD', 'http://dummyimage.com/141x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('cgarriee', 'gboome@sbwire.com', '8FaiFXkAc', 'http://dummyimage.com/240x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('jfillinghamf', 'cpridief@friendfeed.com', 'Pjx34nS2ii', 'http://dummyimage.com/236x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('cselfg', 'aleysong@google.pl', 'ncbP46R', 'http://dummyimage.com/242x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('orojelh', 'wrotheryh@scribd.com', '9o9I2VCYfvH', 'http://dummyimage.com/140x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('acapeloffi', 'tfrancecionei@oakley.com', 'mrXNja', 'http://dummyimage.com/233x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('jcauldfieldj', 'hhardimanj@microsoft.com', 'E4S6iFYwP', 'http://dummyimage.com/156x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('sconybeark', 'sfaughnyk@cmu.edu', 'JbEC0OQo6', 'http://dummyimage.com/183x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('sshatfordl', 'ateall@state.gov', 'zJbAAF2mw0r', 'http://dummyimage.com/103x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('kperhamm', 'luglowm@nps.gov', 's2HbU15S8n', 'http://dummyimage.com/125x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('bbrownsilln', 'cstribblingn@unicef.org', 'SPqMyHkpK', 'http://dummyimage.com/212x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('kloineso', 'lpaveko@w3.org', 'dzATHS6UpF', 'http://dummyimage.com/133x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('hwilkesp', 'gpyzerp@unblog.fr', 'aHzYboW', 'http://dummyimage.com/178x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('tfaunchq', 'estrutleyq@ebay.com', 'JcEc7j6r', 'http://dummyimage.com/212x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('yasletr', 'sdecaviller@huffingtonpost.com', 'YdLXAw', 'http://dummyimage.com/175x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('hthomblesons', 'mclurows@joomla.org', 'K9MLdzodPJ', 'http://dummyimage.com/221x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('umathissent', 'cbeartt@upenn.edu', '986asjKdEHZ', 'http://dummyimage.com/116x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('uschraderu', 'iadamiecu@163.com', 'DUeQ4P', 'http://dummyimage.com/185x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('pboulgerv', 'sspradev@imgur.com', 'D3ibAy5TL', 'http://dummyimage.com/143x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('tgleadhellw', 'sflindersw@pagesperso-orange.fr', '8RLvQUKX', 'http://dummyimage.com/101x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('kcruessx', 'ibunsonx@mysql.com', 'fbFSv7mDH9a', 'http://dummyimage.com/238x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('edivesy', 'jdalessioy@ehow.com', 'Gvhw6S1', 'http://dummyimage.com/196x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('nwhitlowz', 'calvisz@t-online.de', 'LuWhh1Z', 'http://dummyimage.com/241x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('ptarbin10', 'cmoncreif10@linkedin.com', 'B6AIusJ8Whk7', 'http://dummyimage.com/197x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('cfairhead11', 'bbraim11@360.cn', 'jkn0JaEOm', 'http://dummyimage.com/179x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('tfishpool12', 'wborrington12@imgur.com', 'fNuVleks5Alj', 'http://dummyimage.com/199x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('kgrenville13', 'apreshous13@oracle.com', '6xYbv8S7Cb', 'http://dummyimage.com/125x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('ismylie14', 'tbackshill14@google.co.jp', 'dtznEA', 'http://dummyimage.com/123x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('gmccorry15', 'kcrosswaite15@purevolume.com', 'i4t0r1Sy', 'http://dummyimage.com/139x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('ngrand16', 'ffenix16@psu.edu', '9V1W9Qs', 'http://dummyimage.com/204x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('mwaycot17', 'rpitblado17@ovh.net', 'X4G8etMa', 'http://dummyimage.com/104x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('pwolfendale18', 'lmccloid18@tinyurl.com', 'YGhiP5S', 'http://dummyimage.com/112x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('nshannon19', 'rscobbie19@tripod.com', 'L6tDE9Odj', 'http://dummyimage.com/186x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('cmarnane1a', 'edevonside1a@moonfruit.com', 'qiwmZBveEAXs', 'http://dummyimage.com/163x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('wdentith1b', 'rstringman1b@devhub.com', 'ynF2mSGN', 'http://dummyimage.com/187x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('agallaway1c', 'gfirth1c@devhub.com', 'COwdGHDd', 'http://dummyimage.com/118x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('jroughley1d', 'nealden1d@ebay.co.uk', 'UCcL6eu', 'http://dummyimage.com/142x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('wmeneo1e', 'lffrench1e@imdb.com', 'i6pwRWKzm', 'http://dummyimage.com/154x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('fpondjones1f', 'amusk1f@altervista.org', 'HzlegupVh5', 'http://dummyimage.com/137x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('tbenedikt1g', 'bstidson1g@imdb.com', 'd4y3XU1qigDU', 'http://dummyimage.com/167x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('pdalyell1h', 'dheaney1h@mozilla.com', '9WAWBcEV9h', 'http://dummyimage.com/120x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('klicciardo1i', 'pbruinsma1i@time.com', 'F9H18zCC', 'http://dummyimage.com/238x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('apratchett1j', 'sdurrant1j@cnn.com', '9aGIAyBFEx', 'http://dummyimage.com/174x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('bchampagne1k', 'moxbrow1k@lulu.com', 'MUzvVQk', 'http://dummyimage.com/249x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('rhalgarth1l', 'swharram1l@utexas.edu', '5SS1ujzStZoO', 'http://dummyimage.com/214x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('fclemitt1m', 'roheyne1m@boston.com', 'kgW3XqWk3Pg', 'http://dummyimage.com/248x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('asmolan1n', 'sdelue1n@china.com.cn', '69wILgU', 'http://dummyimage.com/122x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('rcopestick1o', 'mthake1o@prweb.com', '3GkkbGgA0', 'http://dummyimage.com/122x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('bcoventry1p', 'cimpson1p@chronoengine.com', 'jN5CJgzN', 'http://dummyimage.com/223x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('cblunt1q', 'cchelley1q@altervista.org', '5wfoPhTBK', 'http://dummyimage.com/104x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('jsvanini1r', 'hizzatt1r@ovh.net', 'GgOuKKl6bwmV', 'http://dummyimage.com/171x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('bdanielot1s', 'knelthorpe1s@mozilla.com', 'iI41X7r3vT', 'http://dummyimage.com/125x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('cwoodrow1t', 'bpellatt1t@ucla.edu', 'r60cRcOe', 'http://dummyimage.com/127x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('sbolus1u', 'jdigle1u@google.ca', 'UJGhVZja3ZV', 'http://dummyimage.com/137x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('grapinett1v', 'ksmiley1v@huffingtonpost.com', '1NXTlHsre', 'http://dummyimage.com/172x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('rruselin1w', 'gbilton1w@creativecommons.org', 'EdYNxtt', 'http://dummyimage.com/137x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('dcashford1x', 'rkisby1x@arizona.edu', 'kzN68qFd', 'http://dummyimage.com/191x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('rbrettell1y', 'dspillard1y@nymag.com', 'ADjfR5wZNHe', 'http://dummyimage.com/111x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('aheinrici1z', 'bdearnaley1z@ft.com', '9bJ7eyB9IADI', 'http://dummyimage.com/152x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('bhamlett20', 'ccaston20@comcast.net', 'DSQSvUxPZhA', 'http://dummyimage.com/195x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('alabrow21', 'cricard21@blogspot.com', '5JTU5W', 'http://dummyimage.com/104x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('mlangley22', 'rcansdill22@twitter.com', 'zicr1pDf', 'http://dummyimage.com/171x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('lpinnion23', 'jfiggs23@indiegogo.com', 'N71uvIkElPOV', 'http://dummyimage.com/250x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('xmccobb24', 'afalco24@toplist.cz', '48ixQWZTo', 'http://dummyimage.com/137x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('dhamblin25', 'sfolley25@tinypic.com', 'A9Tz8e', 'http://dummyimage.com/134x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('meakley26', 'dtumielli26@digg.com', 'eVOzJ5Fe', 'http://dummyimage.com/103x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('vvallentin27', 'njeenes27@networksolutions.com', 'yzUelC', 'http://dummyimage.com/216x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('mkohlerman28', 'airwin28@joomla.org', 'ry4roAp', 'http://dummyimage.com/121x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('ppiller29', 'estjohn29@meetup.com', 'EFmgYbVF7Ohl', 'http://dummyimage.com/154x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('agarbutt2a', 'dianniello2a@nsw.gov.au', 'ArfAECCNNx1', 'http://dummyimage.com/169x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('emclafferty2b', 'tgladwish2b@chronoengine.com', 'VGBN403ts', 'http://dummyimage.com/122x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('ggrealey2c', 'ddarth2c@mapquest.com', '1DMMX4S', 'http://dummyimage.com/217x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('fspeir2d', 'srobichon2d@google.co.uk', 'LrqQiPtEbv', 'http://dummyimage.com/194x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('msiveyer2e', 'gfinker2e@ehow.com', 'Mr77icG3', 'http://dummyimage.com/172x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('ebenez2f', 'abreens2f@ucsd.edu', 'Nycb98V4', 'http://dummyimage.com/215x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('hasmus2g', 'jgilfillan2g@army.mil', 'CY3onM', 'http://dummyimage.com/168x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('mfincke2h', 'lbuxy2h@feedburner.com', 'Cwubo0Y', 'http://dummyimage.com/137x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('mbassano2i', 'hflatman2i@whitehouse.gov', 'a7cyxQcs', 'http://dummyimage.com/126x100.png/5fa2dd/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('bharmson2j', 'seymer2j@wired.com', '2G9uCU1', 'http://dummyimage.com/211x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('zsearles2k', 'rjosum2k@list-manage.com', 'wMN1LXyik89', 'http://dummyimage.com/141x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('snorsworthy2l', 'swinnard2l@hibu.com', 'Bbw1w2eKdwM', 'http://dummyimage.com/164x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('lgoldingay2m', 'jwolfer2m@jalbum.net', 'CWnnk4GS', 'http://dummyimage.com/159x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('rmckennan2n', 'cforlong2n@example.com', 'MffPfus7Dlp', 'http://dummyimage.com/244x100.png/ff4444/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('dbenedidick2o', 'jburchett2o@etsy.com', 'Jw2gCk', 'http://dummyimage.com/151x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('avolkers2p', 'ipaolinelli2p@columbia.edu', '1gKm8XdOPRr', 'http://dummyimage.com/234x100.png/cc0000/ffffff');
      insert into user_entity (username, email, password, "profilePicUrl") values ('loddey2q', 'bhaldene2q@seesaa.net', 'm8S0fIObKW', 'http://dummyimage.com/120x100.png/dddddd/000000');
      insert into user_entity (username, email, password, "profilePicUrl") values ('gspikings2r', 'sthom2r@yahoo.com', 'EE4JqO3', 'http://dummyimage.com/173x100.png/ff4444/ffffff');
    `
    );
  }

  public async down(_: QueryRunner): Promise<void> {}
}
